Repository codeit-bootcamp-frontend/15-Sprint-Mission, pull requests merged in 2025-03, with the labels that each got.

#33 [김지현] sprint2
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  faq.html
  home.html
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/google.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakaotalk.png
  img/logo_big.png
  img/logo_small.png
  img/panda_favicon.png
  img/visibility_off.png
  img/visibility_on.png
  index.html
  items.html
  login.html
  logo.png
  privacy.html
  sign-up.html
  style/global.css
  style/home.css
  style/login.css
  style/reset.css
  style/sign-up.css
Labels: 매운맛🔥

#37 [이찬호] Sprint1
  README.md
  faq.html
  image.png
  index.html
  items.html
  login.html
  privacy.html
  public/icons/ic_facebook.png
  public/icons/ic_instagram.png
  public/icons/ic_twitter.png
  public/icons/ic_youtube.png
  public/images/Img_home_01.png
  public/images/Img_home_02.png
  public/images/Img_home_03.png
  public/images/Img_home_bottom.png
  public/images/Img_home_top.png
  public/logos/Property 1=lg.png
  public/logos/Property 1=lg@2x.png
  public/logos/Property 1=lg@3x.png
  style.css
Labels: 매운맛🔥

#38 [신성오] Sprint 1
  Img_home_bottom.png
  Img_home_top.png
  Property 1=sm.png
  Rectangle 2993.png
  btn_large.png
  btn_small.png
  desktop_02.png
  desktop_03.png
  desktop_04.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  style.css
Labels: 매운맛🔥

#44 [송시은] Sprint2
  css/base.css
  css/home.css
  css/login-signup.css
  css/reset.css
  css/responsive.css
  html/login.html
  html/signup.html
  images/default_photo-1.svg
  images/default_photo.svg
  images/default_photo@2x.svg
  images/dphoto-1.svg
  images/dphoto.svg
  images/dphoto@2x.svg
  images/google_logo.svg
  images/kakao_logo.svg
  index.css
  index.html
Labels: 매운맛🔥

#46 [김서연] - Sprint2
  css/auth.css
  css/style_index.css
  html/faq.html
  html/itmes.html
  html/login.html
  html/privacy.html
  html/signup.html
  image/footer.png
  image/footer.svg
  image/google.png
  image/header.png
  image/header.svg
  image/hot.svg
  image/hotitem.png
  image/kakao.png
  image/logo.svg
  image/logo_title.svg
  image/password_show_icon.svg
  image/password_toggle_icon.svg
  image/register.png
  image/register.svg
  image/search.png
  image/search.svg
  index.html
  privacy.html
  style.css
Labels: 순한맛🐑

#49 [김태일] sprint1
  .github/index.html
  .github/sprint.css
  .gitignore
  FAQ.html
  image/Group.png
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Vector (1).png
  image/Vector.png
  image/ic_facebook.png
  image/panda_market.png
  index.html
  item.html
  logo.html
  privacy_policy.html
  sign-in.html
  style.css
Labels: 매운맛🔥

#53 [김보경] Sprint1
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/img_home_01.png
  img/img_home_02.png
  img/img_home_03.png
  img/img_home_bottom.png
  img/img_home_top.png
  img/logo.png
  index.html
  reset.css
  screencapture-bokyoung-sprint-mission1-netlify-app-2025-03-05-05_16_06.png
  style.css
Labels: 매운맛🔥

#54 [김정우]sprint1
  .github/img/Facebook.png
  .github/img/hukuHeart.png
  .github/img/instagram.png
  .github/img/panda1.png
  .github/img/pandaLa.png
  .github/img/rogo1.png
  .github/img/sq.png
  .github/img/twiter.png
  .github/img/youtube.png
  .github/img/zoom.png
  .github/index.html
  .github/style.css
Labels: 매운맛🔥

#51 Basic 김다인 sprint1
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  images/first_1.png
  images/first_2.png
  images/footer.png
  images/fourth.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/last.png
  images/look.png
  images/nav1.png
  images/nav2.png
  images/second.png
  images/third.png
  index.html
  panda.css
Labels: 순한맛🐑

#55 Basic 유원규 sprint2
  SignUp.html
  img/files.svg
  img/google-icon.svg
  img/hipanda.svg
  img/iconFacebook.svg
  img/iconInsta.svg
  img/iconX.svg
  img/iconYoutube.svg
  img/kakao-icon.svg
  img/like-shirts.svg
  img/loginlogo.svg
  img/logopanda.svg
  img/pandaicon.svg
  img/password_blind.svg
  img/password_eye.svg
  img/serching.svg
  img/talking.svg
  index.html
  login.html
  login_SignUp.css
  loginpage.html
  sprint1.2.css
  sprint2.css
Labels: 매운맛🔥

#59 [유용민] sprint2
  css/pages/login/login.css
  css/pages/main/components/articles.css
  css/pages/main/components/banner.css
  css/pages/main/components/footer.css
  css/pages/main/components/nav.css
  css/reset.css
  css/style.css
  css/variable.css
  img/Img_google_login.png
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/Img_kakao_login.png
  img/Vector.png
  img/Vector1.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/logo.png
  index.html
  screens/join.html
  screens/login.html
Labels: 매운맛🔥

#60 [송시은] Sprint3
  .gitignore
  .prettierrc
  .vscode/settings.json
  css/base.css
  css/home.css
  css/login-signup.css
  css/reset.css
  eslint.config.mjs
  html/login.html
  html/signup.html
  images/webshop.png
  index.html
  package-lock.json
  package.json
Labels: 매운맛🔥

#61 [문주영] Sprint2
  images/Img_logo.png
  images/ic_button_google.svg
  images/ic_button_kakaotalk.svg
  images/ic_eye_invisible.svg
  images/ic_eye_visible.svg
  images/logo_lg.png
  index.html
  login.html
  signup.html
  styles/index.css
  styles/login-signup.css
  styles/reset.css
Labels: 매운맛🔥

#62 [이승민] Sprint1
  css/main.css
  faq.html
  images/home/Img_home_bottom.png
  images/home/Img_home_top.png
  images/home/hotItem-image.png
  images/home/register-image.png
  images/home/search-image.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/socialIcon/facebook-logo.svg
  images/socialIcon/instagram-logo.svg
  images/socialIcon/twitter-logo.svg
  images/socialIcon/youtube-logo.svg
  index.html
  items.html
  login.html
  privacy.html
Labels: 순한맛🐑

#63 [김지현] sprint3
  .github/pull_request_template.md
  img/favicon.png
  img/ic_google.png
  img/ic_kakaotalk.png
  img/logo_big.png
  img/logo_img.png
  img/logo_small.png
  img/logo_text.png
  index.html
  login.html
  sign-up.html
  style/auth.css
  style/global.css
  style/home.css
  style/login.css
  style/sign-up.css
Labels: 매운맛🔥

#64 [오사랑] sprint1
  Frame 2608833.png
  Frame 2608835.png
  Group 19.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Pretendard.otf
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  style.css
Labels: 순한맛🐑

#66 [이한빈] Sprint1
  faq/index.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  style.css
Labels: 매운맛🔥

#71 [조진우]Sprint1
  faq.html
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/login/Component 2.png
  images/login/Component 3.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  items.html
  login.html
  style.css
Labels: 순한맛🐑

#73 [신성오] sprint2
  Img_home_bottom.png
  Img_home_top.png
  Property 1=sm.png
  Rectangle 2993.png
  btn_large.png
  btn_small.png
  desktop_02.png
  desktop_03.png
  desktop_04.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#74 [문혜란] sprint2
  assets/Img_home_01.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/auth_logo.png
  assets/favicon.ico
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/logo.png
  assets/logo_mo.png
  assets/social-google.png
  assets/social-kakao.png
  css/auth.css
  css/palette.css
  css/reset.css
  css/style.css
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#76 [김다인] sprint2
  images/first_1.png
  images/login/google.png
  images/login/kakao.png
  images/login/logo.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  index.html
  login.css
  login.html
  panda.css
  signup.css
  signup.html
Labels: 순한맛🐑

#65 [문수현] Sprint2
  README.md
  assets/Frame 2609420.png
  assets/Group 33677.png
  assets/KakaoTalk_logo.svg
  assets/Property 1=Default.png
  assets/Property 1=Variant2.png
  assets/Property 1=sm.png
  assets/Property 1=sm@3x.png
  assets/desktop_01.png
  assets/desktop_05.png
  assets/footer.png
  assets/gnb.png
  assets/ic_facebook.png
  assets/ic_google.jpg
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/type=solid, status=default.png
  css/styles.css
  faq.html
  index.html
  login.html
  privacy.html
  signup.html
  testfile.txt
Labels: 순한맛🐑

#80 [유원규] Sprint3
  SignUp.html
  css/index.css
  css/loginSignUp.css
  html/SignUp.html
  html/login.html
  img/googleIcon.svg
  img/kakaoIcon.svg
  img/likeShirts.svg
  img/loginlogo.svg
  img/logopanda.svg
  img/padamaketText.svg
  img/pandaLogoIcon.svg
  img/pandaicon.svg
  img/passwordBlind.svg
  img/passwordEye.svg
  img/webshop.png
  index.html
  login.html
  login_SignUp.css
  sprint2.css
Labels: 순한맛🐑

#81 [양지선] sprint2
  .DS_Store
  .gitignore
  deletepart.html
  fnq.html
  images/.DS_Store
  images/Img_home_bottom.png
  images/click_main.png
  images/feature1-image.png
  images/feature2-image.png
  images/feature3-image.png
  images/google_logo.png
  images/img_hotitem.png
  images/img_main.png
  images/img_main2.png
  images/img_resister.png
  images/img_search.png
  images/kakao_logo.png
  images/logo.png
  images/unvisible_eye.png
  images/visible_eye.png
  index.html
  login.html
  privacy.html
  signup.html
  style.css
  style2.css
Labels: 매운맛🔥

#82 [김영현] Sprint3
  css/account.css
  css/common.css
  css/style.css
  html/login.html
  html/signup.html
  images/Preview-Image.jpg
  images/login_img/pandalogo.png
  images/svg/mobile_logo.svg
  index.html
  js/login_password_showing.js
  js/mobile_changeImg.js
Labels: 순한맛🐑

#83 [손수진] Sprint3
  img/logo_noicon.png
  img/opengraph_image.png
  index.html
  login.html
  signup.html
  styles/global.css
  styles/login.css
  styles/style.css
Labels: 매운맛🔥

#86 [김진형]Sprint2
  .vscode/settings.json
  15-Sprint-Mission/images/logo/panda-market-logo.png
  15-Sprint-Mission/index.html
  15-Sprint-Mission/style.css
  15-Sprint-Mission/test.txt
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/logo/favicon.ico
  images/logo/logo.svg
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakao-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  signup.html
  signup_2.html
  style.css
  style_2.css
Labels: help wanted, 순한맛🐑

#89 [전지윤] Sprint3
  common.css
  image/icon/visibility_off.png
  image/icon/visibility_on.png
  image/logo-icon.png
  image/logo-text.png
  image/logotypo.png
  index.html
  login.html
  signup.html
  style.css
Labels: 매운맛🔥

#90 [김수민] Sprint3
  css/auth.css
  css/common.css
  css/layout.css
  css/main.css
  css/reset.css
  images/common/logo_m.svg
  images/common/meta_thumb.png
  images/favicon/manifest.json
  images/sub/logo_big.svg
  index.html
  js/pages/auth.js
  js/script.js
  login.html
  signup.html
Labels: 매운맛🔥

#92 [조인성] Sprint3
  .gitignore
  css/auth.css
  css/index.css
  css/reset.css
  css/responsive.css
  images/icon/ic_facebook.png
  images/icon/ic_google.png
  images/icon/ic_instagram.png
  images/icon/ic_kakaotalk.png
  images/icon/ic_twitter.png
  images/icon/ic_visibility_off.svg
  images/icon/ic_visibility_on.svg
  images/icon/ic_youtube.png
  images/logo/logo_moblie.png
  images/main/img_home_01.png
  images/main/img_home_02.png
  images/main/img_home_03.png
  images/main/img_home_bottom.png
  images/main/img_home_top.png
  images/meta/meta_title.png
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#91 [김영현] Sprint4
  auth/account.css
  auth/login-validation.js
  auth/signup-validation.js
  auth/toggle-password.js
  auth/validation-common.js
  common/common.css
  html/login.html
  images/thumbnail.jpg
  index.html
  pages/faq.html
  pages/index.css
  pages/items.html
  pages/login.html
  pages/privacy.html
  pages/signup.html
  ui/mobile-header-image.js
Labels: 순한맛🐑

#93 [이지현] Sprint3
  assets/icons/Google.png
  assets/icons/Kakao.png
  assets/logo/logo.png
  assets/logo/logo_1.png
  css/common/auth.css
  css/common/reset.css
  css/common/variables.css
  css/pages/home.css
  css/pages/login.css
  css/pages/signup.css
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#94 [명지우] Sprint3
  README.md
  images/Img_logo.png
  images/home_01.png
  images/home_02.png
  images/home_03.png
  images/home_banner_bottom.png
  images/home_banner_top.png
  images/icon_favicon.ico
  images/icon_favicon.png
  images/icon_visibility_on.png
  images/logo.png
  images/preview.png
  index.html
  login.html
  signup.html
  styles/account/account.css
  styles/account/accountPhone.css
  styles/account/accountTablet.css
  styles/account/form.css
  styles/account/header.css
  styles/account/soicalLogin.css
  styles/base.css
  styles/index/banner.css
  styles/index/indexPhone.css
  styles/index/indexTablet.css
  styles/index/section.css
  styles/unsupportedScreen.css
Labels: 매운맛🔥

#97 Basic 유용민 sprint3
  css/components/footer.css
  css/components/nav.css
  css/login/login.css
  css/main/articles.css
  css/main/banner.css
  css/pages/main/components/articles.css
  css/pages/main/components/banner.css
  css/pages/main/components/footer.css
  css/style.css
  img/eye.png
  img/no-eye.png
  index.html
  pages/join.html
  pages/login.html
Labels: 매운맛🔥

#98 [김정우] Sprint2
  .DS_Store
  .github/index.html
  img/Facebook.png
  img/google.png
  img/hukuHeart.png
  img/instagram.png
  img/kakao.png
  img/logo.png
  img/panda1.png
  img/pandaLa.png
  img/sq.png
  img/twiter.png
  img/youtube.png
  img/zoom.png
  index.html
  login.html
  reset.css
  signup.html
  style.css
  styleLogin.css
Labels: 매운맛🔥

#100 [이태식] sprint2
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Property 1=sm.png
  images/Property 1=sm@3x.png
  images/btn_visibility_off.png
  images/btn_visibility_on.png
  images/ic_facebook.png
  images/ic_google.png
  images/ic_instagram.png
  images/ic_kakao.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/img_home_01.png
  images/img_home_02.png
  images/img_home_03.png
  images/img_home_bottom.png
  images/img_home_top.png
  images/logo_lg.png
  images/logo_sm.png
  index.css
  index.html
  login.css
  login.html
  reset.css
  signup.css
  signup.html
  utility.css
Labels: 매운맛🔥

#101 [송시은] Sprint4
  .gitignore
  .vscode/settings.json
  README.md
  auth/auth-validation.js
  auth/auth.css
  auth/login.html
  auth/password-visibility.js
  auth/signup.html
  constants/api-urls.js
  constants/auth-validation-messages.js
  css/base.css
  home/home.css
  images/logo_typo.svg
  images/panda_pink.jpg
  images/panda_pink.png
  index.css
  index.html
  index.js
Labels: 매운맛🔥

#102 [박지섭] sprint2
  assets/icons/icon_google.svg
  assets/icons/icon_invisible_eye.svg
  assets/icons/icon_kakaotalk.svg
  assets/images/img_home_01.png
  assets/images/img_home_02.png
  assets/images/img_home_03.png
  assets/images/img_home_bottom.png
  assets/images/img_home_top.png
  assets/logos/logo_md.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/index.css
  styles/info.css
  styles/login.css
  styles/signup.css
Labels: 매운맛🔥

#103 [문혜란] Sprint3
  assets/img_home_01.png
  assets/img_home_02.png
  assets/img_home_03.png
  assets/img_home_bottom.png
  assets/img_home_top.png
  assets/visibility_off.png
  assets/visibility_on.png
  css/auth.css
  css/palette.css
  css/reset.css
  css/style.css
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#105 [김동한] Sprint3
  auth.css
  common.css
  image/login_page.png
  image/logo.png
  image/mobile_logo.png
  image/singup_page.png
  index.css
  index.html
  login.html
  reset.css
  signup.html
Labels: 매운맛🔥

#106 [유원규] Sprint4
  base.css
  html/SignUp.html
  img/webshop.jpg
  img/webshop.png
  index.css
  index.html
  signin/signin.css
  signin/signin.html
  signin/signin.js
  signup/signup.css
  signup/signup.html
  signup/signup.js
Labels: 순한맛🐑

#110 [맹은빈]Sprint3
  images/icons/eyesIcon.png
  images/metaImage.png
  images/mobileLogo.png
  index.html
  login.css
  pages/login.html
  pages/signup.html
  reset.css
  signup.css
  style.css
Labels: 매운맛🔥

#111 [채미숙] sprint3
  .vscode/extensions.json
  html/login.html
  html/signup.html
  index.html
  login.png
  resources/css/common.css
  resources/css/fonts.css
  resources/css/join.css
  resources/css/main.css
  resources/images/common/btn_visibility_on.png
  resources/images/common/icon_visibility_off.svg
  resources/images/common/icon_visibility_on.svg
  resources/images/common/logo_pandaMarket.png
  resources/images/common/logo_tit.png
  resources/images/panda_thumbnail.png
  signup.png
Labels: 매운맛🔥

#109 [김진형]Sprint3
  faq.html
  index.html
  item.html
  privacy.html
  signin.html
  signup.html
  signup_2.html
  style.css
  style_2.css
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#113 [이찬호] Sprint3
  css/auth-responsive.css
  css/auth.css
  css/banner.css
  css/buttons.css
  css/components.css
  css/feature-elements.css
  css/footer.css
  css/header.css
  css/layout.css
  css/reset.css
  css/responsive.css
  css/typography.css
  css/variables.css
  index.html
  login.html
  public/icons/ic_visibility_off.png
  public/icons/ic_visibility_on.png
  public/images/img_home_01.png
  public/images/img_home_02.png
  public/images/img_home_03.png
  public/images/img_home_bottom.png
  public/images/img_home_top.png
  public/logos/panda-market.png
  public/logos/panda-market2x.png
  signup.html
  style.css
Labels: 매운맛🔥

#114 [김서연] sprint4
  auth/auth.css
  auth/common.js
  auth/login.html
  auth/login.js
  auth/password-visibility.js
  auth/signup.html
  auth/signup.js
  css/common.css
  css/reset.css
  home/index.css
  image/meta_image.png
  index.html
Labels: 순한맛🐑

#115 [김지현] sprint4
  .github/pull_request_template.md
  auth/auth-validation.js
  auth/password-visibility.js
  auth/signin.html
  auth/signup.html
  img/img_preview.png
  index.html
  login.html
  sign-up.html
  style/auth.css
  style/global.css
  style/home.css
Labels: 매운맛🔥

#116 [문주영] Sprint3
  images/home_01.png
  images/home_02.png
  images/home_03.png
  images/home_bottom.png
  images/home_top.png
  images/ic_button_google.svg
  images/ic_button_kakaotalk.svg
  images/ic_google_color.svg
  images/ic_kakaotalk_color.svg
  images/logo.png
  images/logo_text.png
  index.html
  login.html
  signup.html
  styles/auth.css
  styles/color.css
  styles/index.css
  styles/reset.css
Labels: 매운맛🔥

#123 [박재현] sprint3
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  assets/home/footer-hero.webp
  assets/home/header-hero.webp
  assets/home/main-feature1.webp
  assets/home/main-feature2.webp
  assets/home/main-feature3.webp
  assets/icons/footer-fb-icon.webp
  assets/icons/footer-ig-icon.webp
  assets/icons/footer-twt-icon.webp
  assets/icons/footer-yt-icon.webp
  assets/icons/login-google-icon.webp
  assets/icons/login-kakao-icon.webp
  assets/login-logo.png
  assets/logos/login-logo-x1.svg
  assets/logos/login-logo-x2.svg
  assets/logos/nav-logo-mobile.webp
  assets/logos/nav-logo.webp
  faq/index.css
  faq/index.html
  index.css
  index.html
  items/index.css
  items/index.html
  layout/layout.css
  layout/render.js
  login.html
  login/index.css
  login/index.html
  privacy/index.css
  privacy/index.html
  signup.html
  signup/index.css
  signup/index.html
  style.css
  styles/reset.css
  styles/variable.css
Labels: 매운맛🔥

#128 [윤진우] Sprint4
  img/favicon.ico
  index.html
  js/common.js
  js/login.js
  js/signup.js
  login.html
  signup.html
  style/auth.css
  style/base.css
  style/home.css
  style/home_media.css
Labels: 매운맛🔥

#129 [양지선] sprint3
  auth.css
  deletepart.html
  faq.html
  fnq.html
  images/feature1.png
  images/feature2.png
  images/feature3.png
  images/ic_login.png
  images/logo.png
  index.html
  login.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥

#130 [박광민] sprint4
  auth.css
  common.css
  icon-img/logo.svg
  index.html
  login.html
  login.js
  signup.html
  signup.js
  style.css
Labels: 순한맛🐑

#131 [이승민] Sprint3
  .github/pull_request_template.md
  css/auth.css
  css/global.css
  css/layout.css
  index.html
  login.html
  signup.html
Labels: 순한맛🐑

#133 [채미숙] sprint4
  .vscode/extensions.json
  html/faq.html
  html/items.html
  html/login.html
  html/privacy.html
  html/signup.html
  index.html
  resources/css/auth.css
  resources/css/common.css
  resources/css/join.css
  resources/css/main.css
  resources/js/ui_common.js
  resources/js/validation.js
  resources/js/validation_message.js
  resources/js/validation_refac.js
Labels: 매운맛🔥

#134 [조인성] Sprint4
  css/auth.css
  css/common.css
  css/index.css
  css/responsive.css
  css/variables.css
  images/icon/ic_favicon.png
  images/meta/meta_title.png
  index.html
  js/authConstants.js
  js/authEventManager.js
  js/login.js
  js/signUp.js
  login.html
  signup.html
Labels: 매운맛🔥

#135 [박지섭] sprint3
  assets/images/img_preview.png
  assets/logos/logo_lg.png
  assets/logos/logo_sm.png
  assets/logos/logo_typo.png
  index.html
  login.html
  signup.html
  styles/auth/auth.css
  styles/auth/auth_mobile.css
  styles/auth_index.css
  styles/base.css
  styles/home/banner.css
  styles/home/footer.css
  styles/home/header.css
  styles/home/home_mobile.css
  styles/home/home_tablet.css
  styles/home/info.css
  styles/home_index.css
  styles/index.css
  styles/login.css
  styles/reset.css
  styles/signup.css
  styles/typography.css
  styles/unsupported.css
Labels: 매운맛🔥

#138 [명지우] Sprint4
  README.md
  images/icon_visibility_off.png
  images/logo.png
  login.html
  package.json
  scripts/accountValidation.js
  scripts/constants.js
  scripts/models/account.js
  scripts/passwordVisibility.js
  scripts/validation.js
  signup.html
  styles/account/form.css
  styles/account/header.css
  styles/base.css
  styles/index/banner.css
  styles/index/footer.css
  styles/index/header.css
  styles/index/indexPhone.css
  styles/index/section.css
  styles/unsupportedScreen.css
Labels: 매운맛🔥

#139 [김수민] Sprint4
  css/auth.css
  css/common.css
  css/main.css
  images/common/ic_eye_off.svg
  images/common/ic_eye_on.svg
  images/common/meta_preview.png
  index.html
  js/pages/auth.js
  js/script.js
  login.html
  signup.html
Labels: 매운맛🔥

#140 [유용민] sprint4
  css/components/footer.css
  css/components/nav.css
  css/login/login.css
  css/main/articles.css
  css/main/banner.css
  css/style.css
  css/variable.css
  img/eye.png
  index.html
  js/join.js
  js/login.js
  pages/join.html
  pages/login.html
Labels: 매운맛🔥

#141 [문혜란] Sprint4
  css/auth.css
  css/base.css
  css/reset.css
  css/style.css
  index.html
  items.html
  js/common/formValidator.js
  js/login.js
  js/signup.js
  login.html
  package.json
  signup.html
Labels: 매운맛🔥

#142 [신성오] sprint4
  images/Component 2.png
  images/Component 3.png
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Property 1=sm.png
  images/btn_large.png
  images/btn_small.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
  style.css
Labels: 매운맛🔥

#143 [손수진] Sprint4
  img/logo_noicon.png
  img/logo_onlyText.png
  index.html
  login.html
  login.js
  loginFunctions.js
  signup.html
  styles/login.css
  styles/style.css
Labels: 매운맛🔥

#144 [이태식] sprint3
  auth.css
  common.css
  images/ic_visibility_off.png
  images/ic_visibility_on.png
  images/logo_lg.png
  images/logo_sm.png
  images/logo_typo.png
  images/og_image.png
  index.css
  index.html
  login.html
  reset.css
  signup.css
  signup.html
  utility.css
Labels: 매운맛🔥

#146 [맹은빈]Sprint4
  images/icons/eyeOpen.png
  index.html
  login.css
  pages/login.html
  pages/signup.html
  scripts/loginValidate.js
  scripts/passwordIcon.js
  scripts/sigunupValidate.js
  signup.css
  style.css
Labels: 매운맛🔥

#147 [전지윤] sprint4
  css/auth.css
  css/common.css
  css/reset.css
  css/style.css
  image/icon/favicon.ico
  js/auth.js
  js/login.js
  js/package.json
  js/signup.js
  pages/faq.html
  pages/index.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  pages/signup.html
Labels: 매운맛🔥

#148 [유동환] sprint3
  image/logo.png
  image/typography.png
  index.html
  login-Signup.css
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#151 [이승민] Sprint4
  .github/pull_request_template.md
  css/auth.css
  login.html
  scripts/auth.js
  signup.html
Labels: 순한맛🐑

#153 [전유진] sprint3
  css/auth.css
  css/base.css
  css/index.css
  css/login.css
  css/reset.css
  css/unsupported.css
  images/image.png
  images/logo.png
  images/pandamarket.png
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#155 [이지현] Sprint4
  assets/logo/logo.png
  css/common/auth.css
  css/common/variables.css
  css/pages/home.css
  css/pages/login.css
  css/pages/signup.css
  index.html
  login.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  pages/signup.html
  scripts/formValidation.js
  scripts/loginTogglePassword.js
  scripts/loginValidation.js
  scripts/signupTogglePassword.js
  signup.html
Labels: 매운맛🔥

#156 [김보경] sprint2
  colors.css
  img/ic_eye_blind.png
  img/ic_eye_open.png
  img/ic_google.png
  img/ic_kakaotalk.png
  index.html
  login.html
  reset.css
  signup.html
  sprint-mission2-login.png
  sprint-mission2-signup.png
  style.css
Labels: 매운맛🔥

#158 [김태일] Sprint3
  index.html
  sign-in.html
  signup.html
  style/sign-in.css
  style/signup.css
  style/style.css
Labels: 매운맛🔥

#159 [이찬호] Sprint4
  css/auth.css
  css/banner.css
  css/buttons.css
  css/feature-elements.css
  css/responsive.css
  css/sections.css
  css/typography.css
  css/utilities.css
  index.html
  login.html
  public/logos/panda-market.png
  public/logos/panda-market2x.png
  scripts/login.js
  scripts/signup.js
  scripts/validation.js
  signup.html
Labels: 매운맛🔥

#162 [문주영] Sprint4
  login.html
  scripts/auth.js
  signup.html
  styles/auth.css
  styles/color.css
  styles/index.css
  styles/reset.css
Labels: 매운맛🔥
